"""db_criar_banco

Revision ID: 08c9f04af2e9
Revises: 70da55bbe61b
Create Date: 2023-08-17 08:54:54.434978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c9f04af2e9'
down_revision = '70da55bbe61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastro_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('telefone', sa.String(length=14), nullable=False),
    sa.Column('senha', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cadastro_model')
    # ### end Alembic commands ###
